// Generated by CoffeeScript 1.7.1
(function() {
  var command;

  module.exports = command = function() {
    var argv, greet, params;
    greet = require("./index");
    argv = require('minimist')(process.argv.slice(2));
    params = process.argv[2];
    return console.log(greet("Gaolz", argv.drunk));
  };

}).call(this);
