// Generated by CoffeeScript 1.7.1
(function() {
  var greet;

  module.exports = greet = function(name, drunk) {
    if (drunk) {
      return "hello, " + name + " what a sunny day!";
    } else {
      return "hello, " + name;
    }
  };

}).call(this);
